title: "Humphrey Munn"
description: "Robotics & Reinforcement Learning"
url: "https://theresejoseph.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Humphrey Munn"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=TLjiGJIAAAAJ"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/theresejoseph"
  avatar: "/avatar.jpg"
defaults:
  - scope:
      path: ""
    values:
      author_profile: true
analytics:
  provider: "custom"
